<?php

namespace app\modules\admin\controllers;
use app\models\MainBlocks;
use yii\helpers\VarDumper;


/**
 * Default controller for the `admin` module
 */
class DefaultController extends AdminController
{
    public  function beforeAction($action)
    {
        if (\Yii::$app->user->isGuest) {
            return $this->redirect(['/admin/admin/login']);
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        if (\Yii::$app->request->isPost) {
            MainBlocks::saveFromPost(\Yii::$app->request->post())
                ? \Yii::$app->session->setFlash('success', 'Главная страница сайта сохранена!')
                : \Yii::$app->session->setFlash('warning', 'Главная страница сайта не сохранена!');
        }

        $model = MainBlocks::find()->orderBy('index asc')->all();

        return $this->render('index', compact('model'));
    }
}
