<?php

namespace app\controllers;

use Yii;

class FrontendController extends \yii\web\Controller
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function beforeAction($action)
    {
        if (preg_match('/[A-Z]/', Yii::$app->request->absoluteUrl)) {
            return $this->redirect(mb_strtolower(Yii::$app->request->absoluteUrl));
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
